"""
Django settings for invoices_server project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cnr1)^o2$v7qk8(b%5!68^x-s%^i98d&-+iid9ok9)liu91_)5'

# Stripe API klíče
STRIPE_SECRET_KEY = "sk_test_51RhvB0ER45SqKnktB6Rr3ijSRAVrvCkWVFCA74oGlgI2AnBiB26sAhrqMwO3eXKAiwcDO2y2nKbSUBPTdEyQh07I00gCztFwjS"  # svůj tajný klíč ze Stripe dashboardu
STRIPE_PUBLIC_KEY = "pk_test_51RhvB0ER45SqKnktpcFmSkhlKZwhrJHyOQArmZaNrJBRmVtLUP4s6ICqEiMH1l7ckqrmB1UxbYnOVPuPpXpyOqRU00r6r4b1Lx"  # veřejný klíč pro frontend
STRIPE_PRICE_ID = "price_1RhvXUER45SqKnktHRnH7M7z"  # cena nastavená ve Stripe produktu
STRIPE_WEBHOOK_SECRET = "whsec_ce0f4340d6af2f570702ed00cc40b7988c73095903ad433f8dcbff9706eb9dbf"
DOMAIN = "http://localhost:5173"  # nebo tvoje doména později


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'invoices',
    'django_filters',
    'rest_framework',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invoices_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invoices_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CORS_ALLOW_ALL_ORIGINS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "invoices/static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=400),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # pro testování v konzoli
DEFAULT_FROM_EMAIL = 'leonard10@seznam.cz'

EMAIL_HOST = 'leonard10@seznam.cz'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tvuj-uzivatel'
EMAIL_HOST_PASSWORD = 'tvoje-heslo'


