# Generated by Django 5.2 on 2025-07-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_paid_invoice_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
    ]
