# Generated by Django 5.2 on 2025-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
