# Generated by Django 5.2 on 2025-07-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_deleted_at_invoice_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_of', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
